spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_HOST:capgebank}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Capge7878}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.properties.hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}